apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  dataVolumeCapacity: 10G
  image:
    application: {{print "docker.io/confluentinc/cp-server:" .Values.cpServer.version}}
    init: {{print "confluentinc/confluent-init-container:" .Values.confluentInitContainer.version}}
  replicas: 3