apiVersion: batch/v1
kind: Job
metadata:
  name: ldap-add-job
spec:
  template:
    spec:
      containers:
      - name: ldap-add-container
        image: osixia/openldap:1.5.0
        command: ["/bin/sh", "-c"]
        args:
        - ldapadd -x -H "ldap://ldap.ldap-system.svc.cluster.local:389" -D "cn=admin,dc=test,dc=com" -w confluentrox < /ldap/add-user.ldif
        volumeMounts:
        - name: ldap-add-config
          mountPath: /ldap
        env:
        - name: LDAP_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-user-password
              key: password          
      restartPolicy: Never
      volumes:
      - name: ldap-add-config
        configMap:
          name: ldap-add-configmap
  backoffLimit: 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-add-configmap
data:
  add-user.ldif: |
    dn: cn=rui1,dc=test,dc=com
    objectClass: top
    objectClass: person
    objectClass: organizationalPerson
    objectClass: inetOrgPerson
    cn: rui1
    sn: Doe
    givenName: rui1
    uid: rui1
    userPassword: ${LDAP_USER_PASSWORD}