apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: ldap
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - port: 389
    name: ldap
    nodePort: 30389
  - port: 636
    name: ldaps
    nodePort: 30636
  selector:
    app: ldap
