apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: ldap
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 389
    name: ldap
  - port: 636
    name: ldaps
  clusterIP: 10.96.34.116
  selector:
    app: ldap
