apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: {{print "confluentinc/cp-server-connect:" .Values.cpServer.version}}
    init: {{print "confluentinc/confluent-init-container:" .Values.confluentInitContainer.version}}    
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub:
          - name: kafka-connect-datagen
            owner: confluentinc
            version: 0.5.2
  authorization:
    kafkaRestClassRef:
      name: default
      namespace: confluent
    type: rbac
  externalAccess:
    type: nodePort
    nodePort:
      host: confluent.svc.cluster.local
      nodePortOffset: 30022          
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: false
    mds:
      endpoint: http://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-client
      tls:
        enabled: false           