apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: {{print "confluentinc/cp-enterprise-control-center:" .Values.cpServer.version}}
    init: {{print "confluentinc/confluent-init-container:" .Values.confluentInitContainer.version}}
  dataVolumeCapacity: 10Gi
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    # ksqldb:
    # - name: ksqldb
    #   url: http://ksqldb.confluent.svc.cluster.local:8088
    # connect:
    # - name: connect
    #   url: http://connect.confluent.svc.cluster.local:8083