apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: local-kubernetes
nodes:
- role: control-plane
- role: worker
# ArgoCD 
  extraPortMappings:
  - containerPort: 30080 
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker