apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 3
  image:
    application: {{print "confluentinc/cp-schema-registry:" .Values.cpServer.version}}
    init: {{print "confluentinc/confluent-init-container:" .Values.confluentInitContainer.version}}